### ISSUE TITLE
How do you know you're in ketosis?

### ISSUE THREAD

**Issue by amasad** [arielf/weight-loss#1]
Thanks for sharing this.

Can you give me any idea of how much carbs is too much carbs in any single day? And how do you know you're in ketosis? (I know about keto sticks, but having tried this in the past it becomes sort of an obsession that I'd like to avoid)

Related: you mention you could get a way with having a pizza once a week -- wouldn't that kick you off ketosis? If so, how long does it take you to get back into ketosis?

**Comment by arielf** [comment]
Thanks for the comments.  To know whether you're in ketosis, the best way is to measure ketone-bodies in the blood. 

[This wikipedia link is good background](https://en.wikipedia.org/wiki/Ketone_bodies)

To be clear: I'm not claiming I'm in ketosis -- I just clarified this better in the README text. Ketosis is the _extreme_ state you can reach when you restrict calorie intake from carbs to ~20 or less cals/day and I believe it takes a few weeks of this extreme carb restriction to get there. That's the number I've read.  My study is mostly about shifting the (carb, protein, fat) balance _towards_ ketosis and most importantly,  reduce the insulin spikes compared to what I was used to before.

You can definitely lose weight while not being in ketosis (typically about 1 pound/week once you get in the zone).  If you are in ketosis, your weight loss rate should materially increase.  Anyway, that's my current best interpretation of what I see.
