### ISSUE TITLE
Tooth brushing

### ISSUE THREAD

**Issue by djui** [arielf/weight-loss#10]
I know this sounds silly and can be considered as uninteresting as it does not focus on the primary source for weight results, but I am interested to hear if you did record and/or change your tooth brushing behaviour over these three(?) years (e.g. frequency, time of day, using gums, flossing, etc)?

I can see (and frequently experience this as an effect similar to sleep: it expands the fasting times. In times where I only brushed one time per day (before going to bed) I could imagine eating more and feeling more the lust to eat over the day vs brushing my teeth now three times per day, which takes away roughly 2hrs per day I just don't feel like eating. If that would be true (i.e. I don't overcompensate during meals) adding this alongside the "trick" of sleeping enough/long could reduce the potential times of "false decisions" during the day.

**Comment by arielf** [comment]
Very interesting.
I never thought about this.  Doesn't sound silly to me.
So yes, I think it would be great to explore.
