### ISSUE TITLE
Specify what "half-and-half" means

### ISSUE THREAD

**Issue by niieani** [arielf/weight-loss#11]
Specifically in the part: "I switched from milk to half-and-half". My initial reaction was "half and half" of what? But Googling "half-and-half" yields this [wikipedia page](https://en.wikipedia.org/wiki/Half_and_half), so from the context I assumed you meant half-and-half milk and cream, however even those can range in the fat percentage quite widely. 
Could you specify what you meant so that it's clearer for those of us outside of the US?
Thanks. Awesome work, by the way!

**Comment by cwhite92** [comment]
I believe Half and Half is a product in the US, which is basically equal measures of whole milk and light cream (single cream for us Brits?). I've never seen a product like that in the UK, though.

If that's what it really is, here's the nutritional info: https://www.google.co.uk/search?q=half+and+half+nutrition

**Comment by arielf** [comment]
Thanks @cwhite92 
As chite92 wrote, I didn't realize it that this is a US specific term.  It is milk with a very high fat percentage (50% whole milk, and 50% cream, I believe). Anyway it is a standard item in US supermarkets.
