### ISSUE TITLE
Learning the policy which leads to balanced/healthy weight loss?

### ISSUE THREAD

**Issue by usptact** [arielf/weight-loss#12]
What if the problem losing weight could be cast as a problem of finding the best policy? Given the context (day eating habits, moving etc), the policy (to be learned) should output an action (what to do in that day). Am I correctly understanding the learning problem? This would be fun to explore.

**Comment by arielf** [comment]
@usptact I believe you're right. 
Would be great if you could contribute a `vw` contextual-bandit data-set expressing this (with some documentation).
