### ISSUE TITLE
my fitness pal as data store

### ISSUE THREAD

**Issue by colcord** [arielf/weight-loss#13]
Is there a way to use myfitnesspal as a data store as well?
I keep track there of what I eat and how much.
I have started to track my weight there as well.
I'd like to learn which foods are helping and which not so much.
Is there a different app which has a better API?

I am using google fit to automatically record my walking and cycling.
I use Sleep as Android to record my sleep.

I realize that to test some of the current hypotheses, I may have to keep track of additional data, such as the time I eat my meals.

Are there clear enough APIs to be able to do this kind of machine learning?

**Comment by arielf** [comment]
I'm not aware of any.  Any additional contributions from others are very welcome.  That's one of the reasons it is on github.
Note that there's also a `cgi` directory in the source tree which is supposed to provide a very crude web-app (not phone): you upload the data and get the results back, but I didn't have a chance to set up a standalone web site to deploy it on.  Any volunteers to set up this web site are very welcome as well.
