### ISSUE TITLE
Request for details about the specific algorithm used

### ISSUE THREAD

**Issue by ramanamaharshi222** [arielf/weight-loss#17]
This is not an issue but a request to get details about what specific machine learning algorithm was used. This would help in cases where one would want to consider using a different ml package perhaps. Also it would be of great help to the uninitiated if details could be provided about what does the algorithm do. 

Thanks

**Comment by arielf** [comment]
I used vowpal-wabbit (aka `vw`) with mostly vanilla options. It builds a linear model using 3-way enhanced stochastic gradient descent (SGD).  The utility to infer relative weights from a model is called `vw-varinfo` and is included with vowpal wabbit. 

A few references:
- [Vowpal wabbit (wikipedia)](https://en.wikipedia.org/wiki/Vowpal_Wabbit)
- [3-way enhanced SGD](http://stackoverflow.com/questions/32753501/why-normalizing-feature-values-doesnt-change-the-training-output-much/32770631#32770631)
- [Stochastic gradient descent (wikipedia)](https://en.wikipedia.org/wiki/Stochastic_gradient_descent)

**Comment by ramanamaharshi222** [comment]
One follow up question.  Is the algorithm designed to work with data that is missing.  For instance, people do not have the same items every day.  Does the algorithm account for this.

Thanks

**Comment by arielf** [comment]
Yes.

**Comment by ramanamaharshi222** [comment]
Thanks
