### ISSUE TITLE
How-To Section

### ISSUE THREAD

**Issue by sercanov** [arielf/weight-loss#18]
Hi there,

Great work, really admired what you've done here. But for the someone who doesn't know a thing about machine learning, it could be great to have step-by-step reproduction of this mechanism.

Thanks a lot

**Comment by arielf** [comment]
I hear you.

This HOWTO should be easy on Linux Ubuntu/Debian/Mint, mildly more challenging on RedHat or MacOs.  On Windows I would only try in a Ubuntu VM (e.g. busybox).  Give me a bit of time to add it (hopefully very soon).

**Comment by arielf** [comment]
HOWTO.md written.  Ubuntu/Debian should be pretty complete.
Contributions for details on how to install the prerequisites in other environments appreciated (placeholders therein)
