### ISSUE TITLE
OSError: No such file or directory

### ISSUE THREAD

**Issue by sercanov** [arielf/weight-loss#19]
Hi there,

I'd followed your guides on executing the script, installed vw via brew but when I do `make` in the directory, I get the following error.

<img width="953" alt="ekran resmi 2016-09-18 17 12 25" src="https://cloud.githubusercontent.com/assets/10291644/18616379/4ae9c53c-7dc3-11e6-9cc5-9e49f7bba077.png">

I looked it up on stackoverflow, someone says it's related to python subprocess.popen function that command (`vw_cmd`) should be in array of strings, actually it is in that form. I tried with shell=True option but then I get returncode=127. 

The other thing I've tried is executing the command manually where the script breaks, `vw-varinfo2 -k --loss_function squared --progress 1 -l 1.0 --l2 1.85201e-08 sercan.train | tee scores.txt` it doesn't work but when it executed as `./vw-varinfo2`, it works and creates score.txt.

I think it's related to my environment but a help could be great.

Thanks in advance

**Comment by arielf** [comment]
Thanks for the report!

It is a failure of `vw-varinfo2` to find the `vw` executable because the `PATH` setting in the `Makefile` was non-standard.

It should be fixed now. Can you pull and confirm?  Thanks again.

**Comment by sercanov** [comment]
Yeah, it solved it. Thanks a lot.

I've installed R and other dependencies via brew -couldn't found the ggplot2 formula btw-

But when I do `make sc` it throws `/bin/sh: ./score-chart.r: /usr/bin/Rscript: bad interpreter: No such file or directory
make: *** [score-chart] Error 126`

If it just generates charts I don't need it though, I'll try to make it out in JSON.

**Comment by arielf** [comment]
@sercanov 

Thanks again!
Looks like I was missing a dependency.  In Ubuntu/Debian `Rscript` is provided by `r-base-core`.

```
sudo apt-get install r-base-core
```

It is very useful to have `Rscript`, it makes writing scripts in `R` easier.

Not sure what's the equivalent in `brew`.  If you can help here, it'll be appreciated.

Thanks again for all these inputs!  Without this help, I couldn't have made progress.

**Comment by arielf** [comment]
If you're still missing `ggplot2` in `brew`, you can try the alternate route:  call `R`, and install it from within `R` from source as you would install other `R` packages.   The standard way to install a package from within `R` is (needs superuser), from the `R` prompt:

```
install.packages('ggplot2')

# and if this doesn't work, try:
#    ?install.packages
# for more details
```

**Comment by sercanov** [comment]
@arielf I'll try them as soon as I find time, if I could find another way to install it I'll be making a PR for it. Thanks!

**Comment by sercanov** [comment]
Hey there @arielf , I've installed ggplot2 as you described, inside the `R` but still I got the following error when I run `make sc`

```
 /bin/sh: ./score-chart.r: /usr/bin/Rscript: bad interpreter: No such file or directory
make: *** [sc] Error 126
```

Here the R formula info;

<img width="685" alt="ekran resmi 2016-09-24 13 07 56" src="https://cloud.githubusercontent.com/assets/10291644/18807741/f75da3ae-8257-11e6-9cfe-7eac3ca27c74.png">

Could it be related to R installation path ? 
I think the first line of `score-chart.r` is the absolute `Rscript` path, but it's not valid when installed via `brew`.
Then I've tried to make sc with pointing Rscript to local R installation path;
`#!/usr/local/Cellar/r/3.3.1_2/bin/Rscript --vanilla` 

then I get the following error

```
Error in eval(expr, envir, enclos) : 'RelScore' object couldn't find
Calls: ggsave ... by_layer -> f -> <Anonymous> -> f -> lapply -> FUN -> eval
Execution stopped
make: *** [sc] Error 1
```

I think we're close 😋

**Comment by sercanov** [comment]
I guess it's because scores.csv doesn't have the `RelScore` field, It only has `FeatureName` and `Weight`

But in scores.txt `RelScore` points to the `%Weight` right ? So maybe a misnaming ?

**Comment by arielf** [comment]
Pushed some fixes:
- Unfortunately ggplot2() has changed a lot in the recent version and broke several items in the chart.  I had to get rid of the big "Weight Loss' and 'Weight Gain' texts on the chart.
- The varinfo RelScore vs %Weight is now fixed.  Thanks!
- I prefer not to change the top line in the script because the path /usr/local/Cellar/... is very non standard.

**Comment by arielf** [comment]
Also fixed the hardwired path in the shebang line item by calling `Rscript` directly from the `Makefile`
