### ISSUE TITLE
What is the cycling travel distance?

### ISSUE THREAD

**Issue by EddieOne** [arielf/weight-loss#2]
It should also be possible to cut fat and maintain carbs with adequate physical training. So I am curious, what is the cycling distance each day?

**Comment by arielf** [comment]
Mine is a bit short: ~4 miles each way (so ~8 miles total). I imagine things could be better if I biked longer.

**Comment by EddieOne** [comment]
If you want more data, I have a theory on training the body **not** to store fat. There are 2 components to the body hack. First, eat a low fat diet. High fat meals are offset with low calorie ones later. Second, deplete muscle glycogen on a daily basis. For me, 10 miles of daily cycling is more than enough. I learned all this by accident but it has been the best "diet" I've ever done. It's basically awesome food, all the time.
