### ISSUE TITLE
Mac ggplot2 issue

### ISSUE THREAD

**Issue by zachphillips** [arielf/weight-loss#21]
Hi Ariel, thanks so much for your work on this.

I'm working on the Mac instructions for a pull request, and have gotten mostly everything working (it isn't intuitive or even all that Google-able) but for some reason, the chart it's printing out looks like this:

<img width="721" alt="screen shot on 2016-09-25 at 19_17_47" src="https://cloud.githubusercontent.com/assets/636635/18818989/740e2efc-8355-11e6-9293-b10871a49ef9.png">

For the record, I had to change the font from FreeSans, so that could be part of it. I switched to generic Helvetica.

**Comment by zachphillips** [comment]
Yep, I can make the font as small as I want and it still has this issue.

**Comment by arielf** [comment]
Thanks.  It was broken for about a day.  I think the most recent revert fixes this.  Sorry!
Could you verify?  Thanks

Yes, Helvetica should be more portable.  Pull requests always highly appreciated.

**Comment by zachphillips** [comment]
Yep, most recent revert fixes it.
