### ISSUE TITLE
semi-colon in Python

### ISSUE THREAD

**Issue by Mausy5043** [arielf/weight-loss#22]
Hi, 
First off thanks for the great initiative.

What is the purpose of the semi-colon in [line 160 of `vw-varinfo2`](https://github.com/arielf/weight-loss/blob/master/vw-varinfo2#L160) and in [line 352 of same](https://github.com/arielf/weight-loss/blob/master/vw-varinfo2#L352)?

It's just that me and pylinter flag this as an error. But, I just wanted to make sure the semi-colon is not there for some higher purpose ;-)

**Comment by arielf** [comment]
Thanks for the report.

Fixed in commit 9e445d823ccd74c4b228eff9dd592d644b13ebc3
vw-varinfo2: remove semicolons (converting from perl legacy)
