### ISSUE TITLE
Errors with Python 

### ISSUE THREAD

**Issue by sheldonrampton** [arielf/weight-loss#24]
This is a great project. I experienced some errors getting it to run on my laptop, the worst of which were due to my version of Python. I'm running Mac OSX 10.11.6, with Anaconda installed so my default Python version is Python 3.5.1.

This produced a number of syntax errors. For example, line 418 of file vw-varinfo2 throws an invalid syntax error for the line that says:

    sorted_tuples = sorted(F_WEIGHT.items(), key=lambda(k,v): v)
                                                       ^
It didn't like using a tuple as the lambda parameter. I fixed that but then ran into some other syntax errors, so rather than fix them I switched to the version of Python that ships as the default with OSX (Python 2.7.10), and everything ran except that "make sc" still throws the following errors:

```
/usr/local/Cellar/r/3.3.0_1/R.framework/Versions/3.3/Resources/bin/R: line 209: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/Cellar/r/3.3.0_1/R.framework/Versions/3.3/Resources/bin/R: line 209: /usr/local/Library/ENV/4.3/sed: No such file or directory
Fatal error: cannot open file '': No such file or directory
make: *** [sc] Error 2

```

**Comment by arielf** [comment]
@sheldonrampton thanks for the report.

I fixed most of the issues with python3 vs python2 compatibility (including running the 2to3 converter which seems to do a partial job).  There's one issue remaining.  For now I have forced the hashbang line to use `python2`.  You may have both python3 and python2 installed side-by-side, at least on Ubuntu there's no issue having both.

I welcome pull-requests solving the last issue (empty output when running under python3, which may be related to unicode vs byte stream when reading from the `vw` process pipe) so `vw-varinfo2` can work under both pythons. 

The second issue is separate (you should open a separate issue on this) and seems to be a missing `sed`  in your env.  Line 209 in `R` (which is a shell script) indeed calls `sed` via a variable ${SED}.
Do you have `/usr/local/Library/ENV/4.3/sed` on your machine?

**Comment by arielf** [comment]
Closing as main issue is now fixed (calling python2 explicitly).
