### ISSUE TITLE
What does a unexpected "Constant" row mean in output file "scores.txt"?

### ISSUE THREAD

**Issue by blueblued** [arielf/weight-loss#29]
Hi, Arielf, I got something like this(factors in chinese):

FeatureName		HashVal	MinVal	MaxVal	Weight	RelScore
Constant		142054	1.00	1.00	-0.02	-100.00
花生          	    247270	1.00	10.00	-0.01	 -73.55
素三鲜白菜 	    176662	1.00	20.00	-0.00	 -23.43
韭菜鸡蛋饼 	     86006	1.00	20.00	-0.00	 -22.81
......

I don't have any factor "Constant", is it a bug?

**Comment by blueblued** [comment]
I try to replace the chinese factor name to numeric id, and get the same result (The "Constant" row).

Hers is the raw data (with factors' name in numeric format), may you check it and give me any suggestion? Thanks!

======

[ID_foodinfo.csv.txt](https://github.com/arielf/weight-loss/files/1028575/ID_foodinfo.csv.txt)

**Comment by arielf** [comment]
Not a bug. `Constant` is the name of your bias term (aka the intercept of the linear regression)
Also there's no need to replace names by numeric IDs and back.

**Comment by blueblued** [comment]
Got it! Thank you!
