### ISSUE TITLE
Numerical-Weight

### ISSUE THREAD

**Issue by mattkhoury** [arielf/weight-loss#32]
### Can you please explain the (optional) numerical-weight? What is the unit? 

**For example from your journal:**
bagel bread date:1.5   dietsnapple splenda pizza nosleep:0.2
cherry knish cheese   salmon pistachio:0.7 peanut

***

Does this mean you ate 1.5 dates? 

What does this "pistachio:0.7" represent? .7 of a cup?

**Comment by arielf** [comment]
No, it is an optional relative weight.  Relative to 'normal'. Provides finer control over effect.
A fuller explanation appears in the header of the source `ariel.csv`.
