### ISSUE TITLE
Breakfast

### ISSUE THREAD

**Issue by kudkudak** [arielf/weight-loss#5]
First - thanks a lot for sharing that! This is very inspiring :)

Question: many people (and research) say breakfast (breaking fasting :) ) is the most important meal of the day. What are you thoughts on that?

**Comment by arielf** [comment]
Hi (and thanks!) @kudkudak 

My thoughts on that are: we may be different, try it and do what you feel is best for **_you_**.

I have tried various things and I believe I know what's best for me: losing weight really improved my life in many ways.  Ergo: eating when I'm not even feeling hungry (breakfast) just doesn't seem to make sense for me.  I do drink water though, before hopping on my bike :)

Another thought is that there's great value in developing critical thinking, question everything. A lot of people once thought the earth is flat, or the earth is the center of the universe and some (just like today) were even ready to kill others for their different ideas, so I tend to give more weight to what actually works vs. what "experts" say or conventional wisdom. 

Anyway, I hope this makes sense.

**Comment by kudkudak** [comment]
👍 Thanks for the answer

I guess.. closing issue? :)

**Comment by niieani** [comment]
Me and my SO were wondering the same thing as @kudkudak, perhaps there could be a mention somewhere in the readme about the "traditional wisdom of breakfast eating"? I know there were some studies done about potential benefits of breakfast eating, perhaps we could help dig those out?

**Comment by arielf** [comment]
@niieani 
[You can start here - (google search)](https://www.google.com/search?q=is+breakfast+important)

At least from this unscientific search it doesn't seem like the "conventional wisdom" is right. At the very least, many, including doctors, are now questioning it.
