### ISSUE TITLE
Selfies?

### ISSUE THREAD

**Issue by TylerL-uxai** [arielf/weight-loss#7]
Really awesome job reading the data. I like that you were able to consider fasting time and how it relates to sleep. Question: Before and after pictures? Maybe you have a photo around the time of acceleration as well? Thanks

**Comment by arielf** [comment]
Sorry, I'll have to pass on this.  This project required a lot of self-exposure as it is, and it didn't come easy to me. I feel it went far enough. I'll leave the before/after pictures for others.
